/// Flutter icons AddIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AddIcons
///      fonts:
///       - asset: fonts/AddIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AddIcons {
  AddIcons._();

  static const _kFontFam = 'AddIcons';
  static const _kFontPkg = null;

  static const IconData note = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_docs = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
