/// Flutter icons AddIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AddIcons
///      fonts:
///       - asset: fonts/AddIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AddIcons {
  AddIcons._();

  static const _kFontFam = 'AddIcons';
  static const _kFontPkg = null;

  static const IconData note = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
